### PR TITLE
pico: HID input

### PR DESCRIPTION
**Pull request by Daft-Freak**
(Opening this so I don't keep forgetting about it)

USB HID based input for VGA. Draft because I only tested it on three controllers (one of them doesn't work for some reason). Could use some testing on some "common" gamepads (but not xbox stuff as they don't do HID... *sigh*)

What does work is flashing [this uf2 to a PicoSystem](https://github.com/32blit/32blit-sdk/files/8813671/picosystem-gamepad.zip)

Edit: Patch to hardware-test for testing https://github.com/Daft-Freak/32blit-beta/commit/48650294b5a65d4208b9f50ed4e2a0ccc70a4047

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Maybe when I find some gamepads that behave. :laughing: 

(VGA/DVI board + OTG adapter, done!)

**Comment by Daft-Freak** [comment]
Seems more reliable with the new pico-sdk. Also added keyboard support.

**Comment by Gadgetoid** [comment]
OOoh, that's good news!

**Comment by Daft-Freak** [comment]
Still the same two devices working, but I can now switch them (+ a keyboard) around repeatedly without the pico crashing/resetting. 

Also, hubs and multiplayer fun: https://fosstodon.org/@Daft_Freak/109926331926726469

**Comment by Daft-Freak** [comment]
[Slightly modified hardware-test](https://github.com/32blit/32blit-sdk/files/10888976/hardware-test.zip) (displays raw button info at the bottom)

**Comment by Daft-Freak** [comment]
Considering this doesn't affect PicoSystem at all, is there any reason I _shouldn't_ just merge this?

(I've got some USB/multiplayer bits sort-of blocked by this...)

**Comment by ahnlak** [comment]
I can't think of a particularly strong reason *not* to (although, does that imply that you could in theory plug a keyboard into a PicoSystem?)

**Comment by Gadgetoid** [comment]
32blit support for PicoSystem is "unofficial" so I'm okay with it implying things we don't actually support,

This feature may benefit certain other Pico-based projects in the pipeline :laughing:

**Comment by Daft-Freak** [comment]
If you change the board config I guess, but you'd lose the buttons... (USB role is a build-time config here, also you only get one input "driver")

**Comment by Daft-Freak** [comment]
> 32blit support for PicoSystem is "unofficial" so I'm okay with it implying things we don't actually support,

Hmm, yes _someone_ should stop adding support for random things... :laughing: But uh, what does "official support" even mean now?

**Comment by Daft-Freak** [comment]
Now to wait for a "my device doesn't work"/"the buttons are mapped wrong"!

**Comment by mikerr** [comment]
Just got a pimoroni VGAdemo board, 
and tried this out with -DPICO_BOARD=vgaboard 

Yay, my device DOES work ( Logitech F710) and buttons mapped ok using D mode👌

**Pull request merged**
