### PR TITLE
Warning fixes (everywhere)

### PR DESCRIPTION
**Pull request by Daft-Freak**
I made the mistake of looking at my build output.

After reducing the warning count a lot, this also sets the same warning flags as the boilerplate to hopefully catch more warnings. (May result in more commits if actions reports loads)

### CODE REVIEW

**Comment by Daft-Freak** [comment]
... or the actions could just... not run. Warnings must be bad then.

**Comment by Daft-Freak** [comment]
5x the commits later... macOS and MinGW are clean, STM32 has 6 warnings, PicoSystem is mostly fixed by #764, VS is... VS and I'm leaving the clang-tidy stuff in the Linux build for now.

(I ran `clang-tidy` and now I have a... kiloproblem?)
kiloproblem

**Comment by Daft-Freak** [comment]
> (I ran `clang-tidy` and now I have a... kiloproblem?)

Hmm, it's not that bad, https://github.com/Daft-Freak/32blit-beta/commit/d7bd600470c39ca16a5d97284aaefa37417bb4d6 fixes more than half of those (I was bored)

**Comment by Gadgetoid** [comment]
I guess I should merge this *first* and then duck under the maelstrom of merge conflicts :eyes:

**Comment by Daft-Freak** [comment]
Mmm yeah, I really got carried away there didn't I? :laughing:

**Comment by Gadgetoid** [comment]
*QUICK! MERGE* :laughing:

**Pull request merged**
