### PR TITLE
Firmware cleanup

### PR DESCRIPTION
**Pull request by Daft-Freak**
Some code deleting I did a couple of months ago.

- removes code for loading pre-pic games (untested for ages as nothing that old would still run)
- removes remaining parts of the "firmware in ext flash" code
- replaces/cleans up some HAL GPIO code
- tidies up stm32 screen mode handling a little
- removes HAL layers between fatfs and the SD code

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Wow! RIP obsolete exe switching!

Nice work. It's refreshing to see more and more HAL stuff just disappear :laughing:

**Comment by Daft-Freak** [comment]
More small cleanups/space savings. (Ran out of space and slightly forgot about these changes... so found other savings)

**Comment by Gadgetoid** [comment]
Ah does this now fix the ~100 bytes debug build overflow?

**Comment by Gadgetoid** [comment]
Awesome! Thank you.

**Pull request merged**
