### PR TITLE
Update CubeMX project clocks to match final hardware

### PR DESCRIPTION
**Pull request by ali1234**
Final hardware uses a 12MHz crystal on HSE and the PLL dividers are found in main.c.

### CODE REVIEW

**Comment by ali1234** [comment]
Just noticed that there is another one of these in 32blit-hardware repo.

**Comment by Daft-Freak** [comment]
This one is my fault: https://github.com/32blit/32blit-sdk/pull/558, wouldn't be surprised if there's more code that's out-of-sync with the .ioc though.

**Comment by ali1234** [comment]
I checked all the pin assignments and they look okay.

I did a pull against the hardware repo. Maybe we should get rid of the copy here?

**Comment by Gadgetoid** [comment]
Might be sensible to drop the copy here, though now you've corrected it (Thanks, STM32Cube is freakin' awful) it wont ever change again, so it's not like we'll have to keep them in sync.

**Pull request merged**
