### PR TITLE
Pico board config improvements

### PR DESCRIPTION
**Pull request by Daft-Freak**
Splits the big if/else chain in 32blit-pico's CMakeLists into separate config files and the "drivers" into multiple files instead of a giant pile of #ifdefs.

Also includes some of the configs from the "all-the-boards" branch (the ones that don't need much extra code).

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Oh, and removes the pico-extras requirement for devices that don't use it. (PicoSystem most importantly)

**Comment by Gadgetoid** [comment]
Ooooh, veeerryy nice!

I guess this is a huge step toward making this project a little less opinionated about target platforms and a touch more extensible. I think @ali1234 had some thoughts in that direction, but I can't remember where they were mentioned.

**Comment by Daft-Freak** [comment]
At least for anything RP2040-based... 32blit-stm32 remains a bit of a mess. But uh, there's not a huge amount of hardware to target there.

Currently working through the ["everything" branch](https://github.com/Daft-Freak/32blit-beta/commits/pico-all-the-board-configs) attempting to not make things too messy. I think finishing VGA board support might be next...

**Comment by Gadgetoid** [comment]
Le rebase fail? :eyes:

**Comment by Daft-Freak** [comment]
Nope, just forgot to rebase entirely.

(Pressed the resolve button to see what it would do...)

**Comment by Gadgetoid** [comment]
Oh yeah, I'm floored at just how incredibly bad GitHub's integrated conflict resolution is.

**Comment by Gadgetoid** [comment]
Borrowed a little idea from this for Galactic (Blunicorn) Bluetooth Audio. Thanks :laughing:

**Pull request merged**
