### PR TITLE
stm32: "fix" the Reset_Handler warning

### PR DESCRIPTION
**Pull request by Daft-Freak**
Point it to `do_init` (the closest thing to a game's entry point)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Haha, this is the change we've needed all this time :laughing:

**Comment by Gadgetoid** [comment]
Good grief, 27m!? I wonder if we can get a close-enough test of macOS compatibility by just building in Linux with whatever whacky compiler they use. Clang? It's getting a bit silly lately.

**Comment by Gadgetoid** [comment]
Good lord, you're not wrong. ~10min just to compress and upload.

**Comment by ali1234** [comment]
Is that before or after the MacOS minute multiplier?

**Pull request merged**
