### PR TITLE
one liner build script.

### PR DESCRIPTION
**Pull request by shane-powell**
Updates 32Blit.
Removes and recreates build folder and builds everything.
Moves all .blits into single blits folder within build directory.

### CODE REVIEW

**Comment by shane-powell** [comment]
Not sure if you already have something like this. Its not much but it saves me some time.

**Comment by Gadgetoid** [comment]
Oh should probably move this to `tools/`

I could see myself using this, though I have an awful habit of putting things in my build folder that shouldn't be there. 😆 

Jon had something like this called go.sh IIRC. Waaay back when!

I'm surprised nobody has tried to dockerise this yet. 😬

**Comment by shane-powell** [comment]
Moved to tools and tested. :)

**Comment by Daft-Freak** [comment]
Maybe do what the CI does and `-DCMAKE_INSTALL_PREFIX=`$PWD`, then `make install` which would get everything in `build/bin` (including the firmware).

**Comment by Gadgetoid** [comment]
I'm... genuinely shocked I never tried using an install prefix 😆 but yeah that's a really sensible idea.

I guess:

```
cmake .. -DCMAKE_TOOLCHAIN_FILE=../32blit.toolchain -DCMAKE_INSTALL_PREFIX=$PWD
make
make install
```

And then everything is in `bin` and no need to mkdir/copy.

**Comment by Gadgetoid** [comment]
I think it's safe to say this is a little redundant now? We probably support too many host operating systems to make preferring build scripts for one make sense. Could, instead, document the above revelation?

**Comment by Daft-Freak** [comment]
Hmm, I guess the easy thing to do now... is just download the examples from the release files. Only really need to build the SDK itself if you're working on the firmware.

**Comment by Gadgetoid** [comment]
Closed as stale. Thank you all!

**Pull request closed without merging**
