### PR TITLE
Split examples

### PR DESCRIPTION
**Pull request by Daft-Freak**
#744, but moving _everything_. More discussion over there. WIP.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
There's certainly a lot of duplication in the docs... and a lot of the phrase "Set up the 32Blit Makefile from the root of the repository", I feel like that needs rewording somehow.

**Comment by Gadgetoid** [comment]
I really need to stop crashing into bed in the evenings and get onto https://github.com/32blit/32blit-examples/pull/1 :grimacing:

**Comment by Daft-Freak** [comment]
Ah, this is being held up by documentation isn't it?

**Comment by Daft-Freak** [comment]
Well, it's not like I didn't completely forget about this myself...

(Too busy hacking on emulators apparently.)

**Comment by Gadgetoid** [comment]
Not me finding examples in the SDK very, very useful again... 😆

**Comment by Daft-Freak** [comment]
Anything can be "in" the SDK with enough `add_subdirectory`s hacked in. 😆 

(I may have a few extras added most of the time)

**Comment by Daft-Freak** [comment]
Uh kinda, but specifying a specific commit of the examples doesn't seem useful.

**Comment by Gadgetoid** [comment]
Yeah that's a good point, and was nagging away at the back of my mind :laughing:

**Comment by Daft-Freak** [comment]
https://github.com/32blit/32blit-sdk/compare/master...Daft-Freak:32blit-beta:split-examples-2 + https://github.com/32blit/32blit-examples/pull/3 seems to work. Didn't even delete the .sln, it just explodes if the examples aren't there...

**Pull request closed without merging**
