### PR TITLE
pico: More metadata

### PR DESCRIPTION
**Pull request by Daft-Freak**
Adds some helpers for embedding the rest of the metadata into the binary. (author, category and the icon/splash images)

Last commit requires a tools patch https://github.com/Daft-Freak/32blit-tools/commit/9f9adc5b4dbb24911b3f03fd3f05ee185755a474. There's also code in the metadata bot to parse these

### CODE REVIEW

**Comment by Daft-Freak** [comment]
:thinking: Should just need a tools release/version bump now...

**Comment by Gadgetoid** [comment]
Better late than never, I guess - https://github.com/32blit/32blit-tools/releases/tag/v0.7.3

**Comment by Daft-Freak** [comment]
... and it works now. :smile:

**Comment by Gadgetoid** [comment]
Woohoo!

**Pull request merged**
