### PR TITLE
Optimise stretch_blit_sprite

### LINKED ISSUE #221: sprite transform R90 is 1 pixel out of alignment when scaled 2x
When scaled 1x these transforms look normal

```
screen.sprite(sprite, Point(0, 0), Point(0, 0), Vec2(1, 1));
screen.sprite(sprite, Point(0, 8), Point(0, 0), Vec2(1, 1), SpriteTransform::R270);
screen.sprite(sprite, Point(0, 16), Point(0, 0), Vec2(1, 1), SpriteTransform::R90);
```
rotation2

However if you scale 2x the R90 transform becomes misaligned by 1 pixel

```
screen.sprite(explosionLine, Point(0, 0), Point(0, 0), Vec2(2, 2));
screen.sprite(explosionLine, Point(0, 16), Point(0, 0), Vec2(2, 2), SpriteTransform::R270);
screen.sprite(explosionLine, Point(0, 32), Point(0, 0), Vec2(2, 2), SpriteTransform::R90);
```

rotate

### PR DESCRIPTION
**Pull request by Daft-Freak**
Another ~9ms in blit kart, won't affect the non-scaled case (different function). I think also fixes #221 (at least, it fixed something that looked like the same bug in blit kart).

The idea here is similar to the tilemap patch: fill multiple pixels at once if scaling up.

(I was a bit surprised when I measured this, thought it had a much smaller impact...)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
The same optimisation can be applied to `stretch_blit` with great results.

A full-screen upscaled screenshot blit (160x120 being blit to 320x240) takes the launcher frame time from 13.1ms to 9.1ms. This is closer to the ~6.6ms it takes to blit a full resolution, full screen screenshot.

```patch
iff --git a/32blit/graphics/surface.cpp b/32blit/graphics/surface.cpp
index 9906e7f..00faeb2 100644
--- a/32blit/graphics/surface.cpp
+++ b/32blit/graphics/surface.cpp
@@ -474,29 +474,55 @@ namespace blit {
     if (cdr.empty())
       return; // after clipping there is nothing to draw
 
-    float sx = (sr.w) / float(dr.w);
-    float sy = (sr.h) / float(dr.h);
+    static const int fix_shift = 16;
 
-    // offset source rect to accomodate for clipped destination rect
-    uint8_t l = cdr.x - dr.x; // top left corner
-    uint8_t t = cdr.y - dr.y;
+    int scale_x = (sr.w << fix_shift) / dr.w;
+    int scale_y = (sr.h << fix_shift) / dr.h;
 
-    sr.x += (sx * l);
-    sr.y += (sy * t);
+    int left = (dr.x - sr.x) * scale_x;
+    int top = (dr.y - sr.y) * scale_y;
 
-    sr.w = cdr.w * sx;
-    sr.h = cdr.h * sy;
+    int y_step = scale_y;
+    int x_step = scale_x;
 
-    float src_y = sr.y;
-    for (int32_t y = cdr.y; y < cdr.y + cdr.h; y++) {
-      float src_x = sr.x;
-      for (int32_t x = cdr.x; x < cdr.x + cdr.w; x++) {
-        bbf(src, src->offset(src_x, src_y), this, offset(x, y), 1, 1);
+    uint32_t dest_offset = offset(dr);
+    uint32_t src_offset;
 
-        src_x += sx;
-      }
-      src_y += sy;
-    }
+    int y_count = dr.h;
+    int y = top;
+
+    int x_scale_px = sr.w > src->bounds.w ? std::min(dr.w, int32_t((1 << fix_shift) / scale_x)) : 1;
+
+    do {
+      int x_count = dr.w;
+      int x = left;
+
+      int src_step = 1;
+        src_offset = src->offset(sr.x, sr.y + (y >> fix_shift));
+
+      // fill an initial block if we're not part way through a pixel
+      int num = (x & ((1 << fix_shift) - 1)) == 0 ? x_scale_px : 1;
+      do {
+        int new_x = x + x_step * num;
+
+        // can fit another pixel
+        if (x >> fix_shift == new_x >> fix_shift && x_count > num) {
+          num++;
+          new_x += x_step;
+        }
+
+        bbf(src, src_offset + (x >> fix_shift) * src_step, this, dest_offset, num, 0);
+        dest_offset += num;
+
+        x = new_x;
+        x_count -= num;
+
+        num = std::min(x_count, x_scale_px);
+      } while (x_count);
+
+      dest_offset += bounds.w - dr.w;
+      y += y_step;
+    } while (--y_count);
   }
 
   /**
```

Though these functions are now very similar!

**Comment by Gadgetoid** [comment]
I've probably missed something in my hack of this function. I bet it breaks under some cases.

**Comment by Daft-Freak** [comment]
Think you might have some rect mixups in there... I ended up with this similar-looking function:
```c++
void Surface::stretch_blit(Surface *src, Rect sr, Rect dr) {
    Rect cdr = clip.intersection(dr);  // clipped destination rect

    if (cdr.empty())
      return; // after clipping there is nothing to draw

    static const int fix_shift = 16;

    int scale_x = (sr.w << fix_shift) / dr.w;
    int scale_y = (sr.h << fix_shift) / dr.h;

    int left = (cdr.x - dr.x) * scale_x;
    int top = (cdr.y - dr.y) * scale_y;

    uint32_t dest_offset = offset(cdr);
    uint32_t src_offset;

    int y_count = cdr.h;
    int y = top;

    int x_scale_px = dr.w > sr.w ? std::min(cdr.w, int32_t((1 << fix_shift) / scale_x)) : 1;

    do {
      int x_count = cdr.w;
      int x = left;

      src_offset = src->offset(sr.x, sr.y + (y >> fix_shift));

      // fill an initial block if we're not part way through a pixel
      int num = (x & ((1 << fix_shift) - 1)) == 0 ? x_scale_px : 1;
      do {
        int new_x = x + scale_x * num;

        // can fit another pixel
        if (x >> fix_shift == new_x >> fix_shift && x_count > num) {
          num++;
          new_x += scale_x;
        }

        bbf(src, src_offset + (x >> fix_shift), this, dest_offset, num, 0);
        dest_offset += num;

        x = new_x;
        x_count -= num;

        num = std::min(x_count, x_scale_px);
      } while (x_count);

      dest_offset += bounds.w - cdr.w;
      y += scale_y;
    } while (--y_count);
  }
  ```

(Mostly through deleting transform code and find/replace)

**Comment by Gadgetoid** [comment]
Ooo, I wasn't *far* off this- but yeah, totally missed that I should be using the `cdr` ... definitely not rife with confusingly named short variables this code :laughing: no siree.

Confirmed your version works in Palette Swap, even if I set a clipping rectangle.

And... it's somehow faster to do a fullscreen blit? 8.7ms instead of my 9.1 :laughing:

**Comment by Daft-Freak** [comment]
Must be a bit variable, I was getting 9.2ms... so uh, who gets to commit the patch now? :smile:

**Comment by Gadgetoid** [comment]
Just slap it on this PR, if you can!

**Comment by Gadgetoid** [comment]
Thank you!

**Pull request merged**
